workflows:
  expo_android:
    name: Expo Android Build
    max_build_duration: 60
    environment:
      vars:
        EXPO_CLI_VERSION: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install -g expo-cli
          npm install
      - name: Build APK
        script: |
          expo prebuild
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
